# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/iresh/OneDrive/Desktop/sem2/528 asic/ECE-428-Project/Verilog/project_1/project_1.srcs/sources_1/bd/SIG/ip/SIG_sigmoid_0_0/SIG_sigmoid_0_0.xci
# IP: The module: 'SIG_sigmoid_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/iresh/OneDrive/Desktop/sem2/528 asic/ECE-428-Project/Verilog/project_1/project_1.gen/sources_1/bd/SIG/ip/SIG_sigmoid_0_0/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SIG_sigmoid_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/iresh/OneDrive/Desktop/sem2/528 asic/ECE-428-Project/Verilog/project_1/project_1.srcs/sources_1/bd/SIG/ip/SIG_sigmoid_0_0/SIG_sigmoid_0_0.xci
# IP: The module: 'SIG_sigmoid_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/iresh/OneDrive/Desktop/sem2/528 asic/ECE-428-Project/Verilog/project_1/project_1.gen/sources_1/bd/SIG/ip/SIG_sigmoid_0_0/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SIG_sigmoid_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
