# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/SIG/SIG.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SIG || ORIG_REF_NAME==SIG} -quiet] -quiet

# IP: bd/SIG/ip/SIG_ip_wrapper_0_0/SIG_ip_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SIG_ip_wrapper_0_0 || ORIG_REF_NAME==SIG_ip_wrapper_0_0} -quiet] -quiet

# IP: bd/SIG/ip/SIG_sigmoid_0_0/SIG_sigmoid_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SIG_sigmoid_0_0 || ORIG_REF_NAME==SIG_sigmoid_0_0} -quiet] -quiet

# Block Designs: bd/ACC_unit/ACC_unit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ACC_unit || ORIG_REF_NAME==ACC_unit} -quiet] -quiet

# IP: bd/ACC_unit/ip/ACC_unit_acc_ctrl_0_0/ACC_unit_acc_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ACC_unit_acc_ctrl_0_0 || ORIG_REF_NAME==ACC_unit_acc_ctrl_0_0} -quiet] -quiet

# IP: bd/ACC_unit/ip/ACC_unit_acc_0_0/ACC_unit_acc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ACC_unit_acc_0_0 || ORIG_REF_NAME==ACC_unit_acc_0_0} -quiet] -quiet

# XDC: c:/Users/iresh/OneDrive/Desktop/sem2/528 asic/ECE-428-Project/Verilog/project_1/project_1.gen/sources_1/bd/SIG/SIG_ooc.xdc

# XDC: c:/Users/iresh/OneDrive/Desktop/sem2/528 asic/ECE-428-Project/Verilog/project_1/project_1.gen/sources_1/bd/ACC_unit/ACC_unit_ooc.xdc
